[package]
name = "chip8ui"
version = "0.1.0"
authors = ["Markus Hedvall <mackanhedvall@gmail.com>"]

[dependencies]
chip8core = { path = "../chip8core" }

piston = "0.24.0"
pistoncore-sdl2_window = "0.33.0"
piston2d-graphics = "0.16.0"
piston2d-opengl_graphics = "0.31.0"
